modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "mixson_rosetta"
version = "${version}"
displayName = "Mixson Rosetta"
authors = "Rasa Novum"
description = '''
Server-owned datapack asset synchronization for Mixson and Rosetta
'''

[[dependencies.mixson_rosetta]]
modId = "neoforge"
type = "required"
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mixson_rosetta]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.mixson_rosetta]]
modId = "mixson"
type = "required"
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mixson_rosetta]]
modId = "rosetta_library"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
