modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "runeweaver_rosetta"
version = "${version}"
displayName = "Runeweaver Rosetta"
authors = "xameryn"
description = '''
Server-owned datapack asset synchronization for Runeweaver and Rosetta
'''

[[dependencies.runeweaver_rosetta]]
modId = "neoforge"
type = "required"
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.runeweaver_rosetta]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.runeweaver_rosetta]]
modId = "runeweaver"
type = "required"
versionRange = "[${version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.runeweaver_rosetta]]
modId = "rosetta_library"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
